---
name: Performance Issue
description: Report a performance problem with one or more games within UFO 50.
title: "[Performance Issue]: "
labels:
  - performance-bug
body:
  - type: markdown
    attributes:
      value: >
        Report a performance issue with one or more of the games within UFO 50.
        Keep in mind this is for the PortMaster port, which runs on small-arm
        handheld devices with low-end processors and memory. Please use a
        descriptive title and include as much detail as possible. DO NOT OPEN DUPLICATE ISSUES! Double check other open reports before submitting. Thank you.
  - type: input
    id: ufo50-games
    attributes:
      label: UFO 50 Game(s)
      description: Which one or more UFO 50 games had the performance issue?
      placeholder: Write game(s) here
    validations:
      required: true
  - type: input
    id: device-type
    attributes:
      label: Device Type
      description: Which supported PortMaster Handheld are you using?
      placeholder: e.g. Anbernic RG35xx Plus
    validations:
      required: true
  - type: input
    id: cfw-type
    attributes:
      label: Firmware Type
      description: Which firmware are you running?
      placeholder: e.g. Knulli, ArkOS, MuOS, etc
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Describe the issue here, if it is reproducible, if it has specific conditions, etc.
  - type: markdown
    attributes:
      value: >
        Please attach any logs you have including ports/ufo50/log.txt and ports/ufo50/patchlog.txt.
